//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khanar_Dokan.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        [Key]
        public int cid { get; set; }

        public int uid { get; set; }

        public int fid { get; set; }

        [Required]
        public string comment1 { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual User User { get; set; }
    }
}
