//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khanar_Dokan.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contuct
    {
        [Key]
        public int Comnid { get; set; }

        [Required]
        public string Comnname { get; set; }

        [Required]
        public string Comnemail { get; set; }

        public string Comnsubject { get; set; }

        [Required]
        public string Comnmessage { get; set; }

        public string Comnstatus { get; set; }
    }
}
