//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khanar_Dokan.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        [Key]
        public int InvoiceNumber { get; set; }

        public int uid { get; set; }

        public System.DateTime OrderDate { get; set; }

        public decimal Subtotal { get; set; }

        public string ShipMethod { get; set; }

        public decimal Shipping { get; set; }

        public decimal SalesTax { get; set; }

        public decimal Total { get; set; }

        [Required]
        public string CreditCardType { get; set; }

        [Required]
        public string CardNumber { get; set; }

        [Required]
        public int ExpirationMonth { get; set; }

        [Required]
        public int ExpirationYear { get; set; }
    
        public virtual User User { get; set; }
    }
}
